resource/aws_ebs_volume: Always set all attributes in Terraform state, suppress difference for iops with non-io1 type
The Terraform 0.12 Provider SDK acceptance testing framework was picking up the lack of the `iops` attribute being set during `ImportStateVerify` testing. Here we prefer to always set all attributes into the Terraform state and ignore the difference for the `iops` attribute as necessary.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAWSEBSVolume_basic (15.45s)
    testing.go:568: Step 0 error: Check failed: Check 4/8 error: aws_ebs_volume.test: Attribute 'iops' found when not expected

--- FAIL: TestAccAWSEBSVolume_kmsKey (38.24s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=4) "iops": (string) (len=1) "0"
        }

--- FAIL: TestAccAWSEBSVolume_updateAttachedEbsVolume (127.89s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=4) "iops": (string) (len=1) "0"
        }

--- FAIL: TestAccAWSEBSVolume_updateSize (19.08s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=4) "iops": (string) (len=1) "0"
        }

--- FAIL: TestAccAWSEBSVolume_updateType (19.01s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=4) "iops": (string) (len=1) "0"
        }

--- FAIL: TestAccAWSEBSVolume_withTags (19.11s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=4) "iops": (string) (len=1) "0"
        }
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSEBSVolume_NoIops (24.99s)
--- PASS: TestAccAWSEBSVolume_basic (25.08s)
--- PASS: TestAccAWSEBSVolume_withTags (25.21s)
--- PASS: TestAccAWSEBSVolume_updateIops (44.99s)
--- PASS: TestAccAWSEBSVolume_updateSize (45.46s)
--- PASS: TestAccAWSEBSVolume_updateType (45.51s)
--- PASS: TestAccAWSEBSVolume_kmsKey (55.31s)
--- PASS: TestAccAWSEBSVolume_updateAttachedEbsVolume (193.59s)
```